services:

    leos.abstract.repository:
        abstract: true
        factory: ["@doctrine.orm.entity_manager", "getRepository"]

    leos.event.dispatcher:
        class: Leos\Infrastructure\CommonBundle\Event\EventDispatcher
        public: true
        autowire: true

    leos.event.collector:
        class: Leos\Domain\Common\Event\EventCollector
        factory: ["Leos\\Domain\\Common\\Event\\EventCollector", "instance"]
        public: true

    leos.event.bus.middleware.publisher:
        class: Leos\Infrastructure\CommonBundle\Bus\Middleware\EventDispatcherMiddleware
        autowire: true
