services:

    leos.abstract.repository:
        abstract: true
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        public: false

    leos.abstract.form_factory:
        abstract: true
        arguments: ["@form.factory"]

    leos.event.dispatcher:
        class: Leos\Infrastructure\CommonBundle\Event\EventDispatcher
        public: true
        autowire: true

    leos.event.collector:
        factory: Leos\Infrastructure\CommonBundle\Event\EventCollector:instance

    leos.event.bus.middleware.publisher:
        class: Leos\Infrastructure\CommonBundle\Bus\Middleware\EventDispatcherMiddleware
        autowire: true
