old_sound_rabbit_mq:
    connections:
        default:
            host:     'rmq'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

    producers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }

    consumers:
        events:
            connection:       default
            exchange_options: { name: 'events', type: topic }
            queue_options:
              name: events
              routing_keys:
                  - 'UserWasCreated'
            callback:         leos.evens.async.consumer.events