version: '2'
services:
  nginx:
    build: nginx
    depends_on:
      - fpm
    ports:
      - "80:80"
    volumes_from:
      - fpm

  fpm:
    image: jorge07/alpine-php:7.1-dev-sf
    ports:
      - "2323:22"
      - "9000:9000"
    volumes:
      - "$PWD:/app"
    depends_on:
      - mysql

  redis:
    image: redis:3.2-alpine

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ddd
    volumes:
      - db_data:/var/lib/mysql

  rmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  db_data:
